  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-ubuntu-latest
          path: ./release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Simple auto-release with build artifact.
          files: ./release/build_info.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: release
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy dummy
        run: |
          echo "Deploying... pretend this is a real server deployment."
